{% set name = "simple_template" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1f782c744d122f5d2b7d75b387019ec397e4f878665f5a2ed7f668801686e705

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip >=23.0
  run:
    - python >={{ python_min }}
test:
  imports:
    - simple_template
  commands:
    - pip check
    - pytest
  source_files:
    - tests
    - pyproject.toml
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/Fraetor/simple_template
  summary: Simple placeholder-filling template library.
  dev_url: https://github.com/Fraetor/simple_template
  license: 0BSD
  license_file: LICENCE

extra:
  recipe-maintainers:
    - Fraetor
